services:
  postgres:
    image: postgres:16
    container_name: dms_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dms
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dms_redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  minio:
    image: minio/minio
    container_name: dms_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

volumes:
  pg: {}
  minio: {}
